### ISSUE TITLE
Build fails on OSX 10.10.2

### ISSUE THREAD

**Issue by aptituz** [knu/ruby-unf_ext#10] opened 2015-04-19 17:40 UTC
Hi there,

when trying to build and install beaker I've noticed that unf_ext fails to build:

uilding native extensions.  This could take a while...
ERROR:  Error installing unf_ext:
    ERROR: Failed to build gem native extension.

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
```

checking for main() in -lstdc++... yes
creating Makefile

make "DESTDIR="
compiling unf.cc
In file included from unf.cc:1:
In file included from ./unf/normalizer.hh:4:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:265:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__bit_reference:15:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:628:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:604:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found
# include <__debug>

```
     ^
```

1 error generated.
make: **\* [unf.o] Error 1

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/unf_ext-0.0.7.1 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/unf_ext-0.0.7.1/ext/unf_ext/gem_make.out

Any change to fix this? Tell me, if you need further information.

Thanks and best Regards,
Patrick

**Comment by knu** [comment] 2015-04-20 03:44
It doesn't reproduce for me with OS X 10.10.3 and Xcode 6.3, but there seem to be some people in the same boat as you.  Try fixing your installation as described here: http://stackoverflow.com/questions/29529455/missing-c-header-debug-after-updating-osx-command-line-tools-6-3

**Comment by aptituz** [comment] 2015-04-20 06:11
Thanks for the hint. I'll first try, if the missing update of my system
will already fix it. Otherwise I'll have a look at the described stuff.

2015-04-20 5:44 GMT+02:00 Akinori MUSHA <notifications@github.com>:

**Comment by aptituz** [comment] 2015-04-20 06:59
Upgrading OSX did not work. Downgrading to Xcode 6.2 worked. JFTR.

2015-04-20 8:11 GMT+02:00 Patrick Schönfeld <patrick.schoenfeld@gmail.com>:

**Comment by espen** [comment] 2015-04-23 12:26
Apple updated Command Line Tools to version 6.3 which fixes this.

**Comment by aptituz** [comment] 2015-04-26 13:11
Good to know. Thanks for the hint.

**Comment by gertig** [comment] 2015-09-20 18:06
This may also be due to not having agreed to the Xcode license agreements. I had this same issue and after launching Xcode and agreeing to the license agreement the problem was solved.

**Comment by pioto** [comment] 2015-10-01 16:45
I'm using ruby from MacPorts, and found the fix for this issue was to also install GCC from MacPorts:

```
sudo port install apple-gcc42
sudo port select gcc apple-gcc42
```

**Comment by peterc** [comment] 2015-11-10 15:54
I had the same problem, but found it was simply because I hadn't accepted the T&Cs after Xcode updated itself without me noticing. So if you have this issue, try running gcc -v first to make sure it runs..

**Closed** 2017-04-11 08:40 UTC
